---
name: Create release PR

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * 3'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Create release PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          gh auth setup-git

          git fetch origin release:release

          if [[ $(git merge-base main release) == $(git rev-parse main) ]]; then
              echo "No changes found in main, skip PR creation"
              exit 0
          fi

          branch="release-candidate-${GITHUB_RUN_ID}"

          while IFS= read -r -d '' config; do
            sed -i 's/#main/#release/g' "${config}"
          done < <(git ls-files -z -- '*.json')

          git ls-files -z -- '*.json' | git add --pathspec-from-file=- --pathspec-file-nul

          git switch -c "${branch}"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "Promote main configuration to release"
          git push --set-upstream origin "${branch}"

          gh pr create \
            --base release \
            --head "${branch}" \
            --title "Release week $(date -u +%V)" \
            --body "Automatically created PR to merge main into release"

          gh auth logout