---
name: Run renovate-config-validator

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Validate config 
        run: |
          docker run --entrypoint=renovate-config-validator --volume "$(pwd):/tmp" renovate/renovate:slim /tmp/default.json
