# Runs renovate for this repository.
name: Renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
      configMigration:
        description: "Toggle PRs for config migration"
        required: false
        default: "true"
        type: string

  schedule:
    - cron: '30 4,6 * * 1-5'

permissions:
  contents: read
  id-token: write

jobs:
  call-workflow:
    uses: rancher/renovate-config/.github/workflows/renovate-vault.yml@release
    with:
      configMigration: ${{ inputs.configMigration || 'true' }}
      logLevel: ${{ inputs.logLevel || 'info' }}
      overrideSchedule: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
    secrets: inherit
