name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - run: make validate

  call-workflow-push:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write

    uses: ./.github/workflows/renovate-vault.yml
    with:
      configMigration: 'true'
      logLevel: 'debug'
      overrideSchedule: "{'schedule':null}'"
      renovateConfig: ${{ inputs.renovateConfig || '.github/renovate.json' }}
      dryRun: 'full'

  # If the PR comes from a fork, the token will be a read-only and without
  # `id-token`, so we pass (override) this token to allow properly testing the
  # PR and skipping the Vault step.
  call-workflow-pr:
    if: github.event.pull_request.head.repo.fork
    permissions:
      contents: read
      id-token: write

    uses: ./.github/workflows/renovate-vault.yml
    with:
      configMigration: 'true'
      logLevel: 'debug'
      overrideSchedule: "{'schedule':null}'"
      renovateConfig: ${{ inputs.renovateConfig || '.github/renovate.json' }}
      dryRun: 'full'
    secrets:
      override-token: ${{ secrets.GITHUB_TOKEN }}
